# Generated by Django 5.2.6 on 2025-10-07 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_profile_thana'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='ক্লাসের নাম')),
            ],
            options={
                'verbose_name': 'ক্লাস',
                'verbose_name_plural': 'ক্লাসসমূহ',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='বিষয়ের নাম')),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='core.classname', verbose_name='ক্লাস')),
            ],
            options={
                'verbose_name': 'বিষয়',
                'verbose_name_plural': 'বিষয়সমূহ',
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='অধ্যায়ের নাম')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chapters', to='core.subject', verbose_name='বিষয়')),
            ],
            options={
                'verbose_name': 'অধ্যায়',
                'verbose_name_plural': 'অধ্যায়সমূহ',
            },
        ),
    ]
