# Generated by Django 5.2.6 on 2025-10-08 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_classname_subject_chapter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classname',
            options={'verbose_name': 'ক্লাস', 'verbose_name_plural': 'ক্লাস সমূহ'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'প্রোফাইল', 'verbose_name_plural': 'প্রোফাইল সমূহ'},
        ),
    ]
