# Generated by Django 5.2.6 on 2025-10-08 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_classname_options_alter_profile_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('program_name', models.CharField(max_length=255)),
                ('question_type', models.CharField(choices=[('mcq', 'বহু নির্বাচনি'), ('creative', 'সৃজনশীল'), ('combined', 'সমন্বিত প্রশ্ন')], max_length=50)),
                ('number_of_questions', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chapters', models.ManyToManyField(to='core.chapter')),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.classname')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subjects', models.ManyToManyField(to='core.subject')),
            ],
        ),
    ]
