# Generated by Django 5.2.7 on 2025-10-08 07:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_questionpaper'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='প্রশ্ন')),
                ('question_type', models.CharField(choices=[('mcq', 'বহু নির্বাচনি'), ('creative', 'সৃজনশীল'), ('short', 'সংক্ষিপ্ত উত্তর')], default='mcq', max_length=50)),
                ('option_a', models.TextField(blank=True, null=True)),
                ('option_b', models.TextField(blank=True, null=True)),
                ('option_c', models.TextField(blank=True, null=True)),
                ('option_d', models.TextField(blank=True, null=True)),
                ('correct_option', models.CharField(blank=True, max_length=2, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.chapter')),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.classname')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.subject')),
            ],
            options={
                'verbose_name': 'প্রশ্ন',
                'verbose_name_plural': 'প্রশ্নসমূহ',
            },
        ),
        migrations.AddField(
            model_name='questionpaper',
            name='questions',
            field=models.ManyToManyField(blank=True, to='core.question'),
        ),
    ]
