# Generated by Django 5.2.7 on 2025-10-12 03:23

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_question_options_alter_question_option_a_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='chapter',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='subject', chained_model_field='subject', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.chapter'),
        ),
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='class_name', chained_model_field='class_name', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='core.subject'),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='chapters',
            field=smart_selects.db_fields.ChainedManyToManyField(chained_field='subjects', chained_model_field='subject', horizontal=True, to='core.chapter'),
        ),
        migrations.AlterField(
            model_name='questionpaper',
            name='subjects',
            field=smart_selects.db_fields.ChainedManyToManyField(chained_field='class_level', chained_model_field='class_name', horizontal=True, to='core.subject'),
        ),
    ]
