# Generated by Django 5.2.7 on 2025-10-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_question_chapter_alter_question_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(blank=True, choices=[('mcq', 'Multiple Choice'), ('short', 'Short Answer'), ('creative', 'Creative')], max_length=20),
        ),
    ]
