# Generated by Django 5.2.7 on 2025-10-13 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_question_question_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(choices=[('sa', 'সাধারন প্রশ্ন'), ('tp', 'টেস্ট পেপার প্রশ্ন'), ('bd', 'বোর্ড প্রশ্ন')], default='sa', max_length=2, verbose_name='ক্যাটাগরি'),
        ),
    ]
